### PR TITLE
Fix typo s/calcuation/calculation

### PR DESCRIPTION
**Pull request by kinow**
Fix typo.

Thanks for the great tool by the way.
Bruno

### CODE REVIEW

**Comment by tsdgeos** [comment]
Thanks for your contribution :)

This repository is a mirror a KDE repository. For this reason we can't accept contributions through Github. Please see https://community.kde.org/Infrastructure/Github_Mirror for details on how to contribute to this and other KDE projects.

**Comment by milianw** [comment]
I'm also OK with manually merging contributions I get via github, reopening this until I land it in master.

Albert, please don't close stuff in heaptrack.

**Comment by tsdgeos** [comment]
Thanks for your contribution :)

This repository is a mirror a KDE repository. For this reason we can't accept contributions through Github. Please see https://community.kde.org/Infrastructure/Github_Mirror for details on how to contribute to this and other KDE projects.

**Comment by milianw** [comment]
oh, a bot - how nasty :(

**Comment by kinow** [comment]
I contributed to Krita before via patches (never through phabricator). So can definitely send the patch via bugzilla if that's better? Otherwise, @milianw, even better if you can manually apply the patch. Even if it's not with my user. What is important is that we fix this trivial typo anyway :) Thanks, Bruno

**Comment by tsdgeos** [comment]
@milianw This was discussed and agreed in kde-devel mailing list as the only sane way gone forward since we had hundreds of open pull requests no one was looking at.

**Comment by milianw** [comment]
merged, thanks @kinow

**Pull request closed without merging**
