### PR TITLE
Add support for the mimalloc allocator

### PR DESCRIPTION
**Pull request by MasterDuke17**
This way allocations/free done by it are tracked regardless of whether
it's used via a dynamic override (e.g., preload) or directly via api.

### CODE REVIEW

**Review by milianw — CHANGES_REQUESTED** [review]
hey there!

this looks good but you are missing changes to heaptrack_inject which uses a slightly different mechanism and needs to be expanded for these functions too please

**Comment by MasterDuke17** [comment]
> this looks good but you are missing changes to heaptrack_inject which uses a slightly different mechanism and needs to be expanded for these functions too please

I'm not sure how to test the heaptrack_inject mechanism, but this seems likely to be the correct change (i.e., it compiles, ship it!).

**Comment by MasterDuke17** [comment]
Easy enough, and yep, results looked good.

**Comment by milianw** [comment]
I just tried it on an app that's not using mimalloc and that then fails b/c we fail to find the original mimalloc entry points. the code needs to be changed to take that into account - i.e. this shouldn't be a fatal error for the mimalloc functions:

```
Could not find original function mi_malloc
```

**Comment by MasterDuke17** [comment]
My bad. I'm not sure how you want this to be handled, but
```patch
diff --git src/track/heaptrack_preload.cpp src/track/heaptrack_preload.cpp
index 4147f15..b5d4b5f 100644
--- src/track/heaptrack_preload.cpp
+++ src/track/heaptrack_preload.cpp
@@ -54,7 +54,7 @@ struct hook
     void init() noexcept
     {
         auto ret = dlsym(RTLD_NEXT, Base::identifier);
-        if (!ret) {
+        if (!ret && strstr(Base::identifier, "mi_") != Base::identifier) {
             fprintf(stderr, "Could not find original function %s\n", Base::identifier);
             abort();
         }
```
seems to work for me (i.e., everything looks the same for mimalloc-using applications, and no errors+normal-looking results for non-mimalloc-using applications).

**Comment by MasterDuke17** [comment]
@milianw should I push the patch I showed? Or do you have a different way in mind?

**Comment by milianw** [comment]
yes, that would be acceptable. Any alternative approach I could then add after the fact. I'll handle this now and merge the code. Note that this will happen outside the github ui (b/c heaptrack is actually only mirrored here, the real upstream is over at invent.kde.org)

**Comment by milianw** [comment]
Done now, many thanks again for your contribution

**Pull request closed without merging**
